version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yourdb

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4173:5173"  # Changed to port 4173
    depends_on:
      - server

volumes:
  mongodb_data: